### ISSUE TITLE
betamax recorder records responses overzealously

### ISSUE THREAD

**Issue by jamesarosen** [simplereach/ember-cli-betamax#6]
https://github.com/simplereach/ember-cli-betamax/blob/677b815201c6003ef53f9cf33c4f21034a98752f/test-support/helpers/betamax-recorder.js#L45 is

``` js
if(!allResponseUrls['url']) {
```

but I think it should be

``` js
if(!allResponseUrls[url]) {
```

As written, it records _every_ response because `allResponseUrls` never contains the string `'url'` since that's not a valid XHR url.

**Comment by andremalan** [comment]
@jamesarosen sorry I missed this earlier (for some reason my notifications for this repo were off). 

Good catch, I was wondering why my cassette just blew over 100MB!
